// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: tcp/tcp.proto

package tcp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TcpClient is the client API for Tcp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TcpClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Tcp_ConnectClient, error)
}

type tcpClient struct {
	cc grpc.ClientConnInterface
}

func NewTcpClient(cc grpc.ClientConnInterface) TcpClient {
	return &tcpClient{cc}
}

func (c *tcpClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Tcp_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &Tcp_ServiceDesc.Streams[0], "/tcp.Tcp/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &tcpConnectClient{stream}
	return x, nil
}

type Tcp_ConnectClient interface {
	Send(*Packet) error
	Recv() (*Packet, error)
	grpc.ClientStream
}

type tcpConnectClient struct {
	grpc.ClientStream
}

func (x *tcpConnectClient) Send(m *Packet) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tcpConnectClient) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TcpServer is the server API for Tcp service.
// All implementations must embed UnimplementedTcpServer
// for forward compatibility
type TcpServer interface {
	Connect(Tcp_ConnectServer) error
	mustEmbedUnimplementedTcpServer()
}

// UnimplementedTcpServer must be embedded to have forward compatible implementations.
type UnimplementedTcpServer struct {
}

func (UnimplementedTcpServer) Connect(Tcp_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedTcpServer) mustEmbedUnimplementedTcpServer() {}

// UnsafeTcpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TcpServer will
// result in compilation errors.
type UnsafeTcpServer interface {
	mustEmbedUnimplementedTcpServer()
}

func RegisterTcpServer(s grpc.ServiceRegistrar, srv TcpServer) {
	s.RegisterService(&Tcp_ServiceDesc, srv)
}

func _Tcp_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TcpServer).Connect(&tcpConnectServer{stream})
}

type Tcp_ConnectServer interface {
	Send(*Packet) error
	Recv() (*Packet, error)
	grpc.ServerStream
}

type tcpConnectServer struct {
	grpc.ServerStream
}

func (x *tcpConnectServer) Send(m *Packet) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tcpConnectServer) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Tcp_ServiceDesc is the grpc.ServiceDesc for Tcp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tcp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tcp.Tcp",
	HandlerType: (*TcpServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Tcp_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tcp/tcp.proto",
}
